spring:
  resources:
    static-locations: file:build,classpath:/public,classpath:/static
  http:
    converters:
      preferred-json-mapper: gson
  gson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    pretty-printing: false
server:
  servlet:
    session:
      timeout: 5m
logging:
  level:
    root: ERROR
  file:
    max-size: 2MB
    max-history: 1
  path: ./logs
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSZ
app:
  api-base-url: /api
  public-urls:
  - /manifest.json
  - /favicon.ico
  guest:
    username: GUEST
    password: $2a$10$5V6Rvp4GGAKu9.TpIG1usus/x07SoNxwh9zfW73KqaMg7LwQ3VcUu
 