export const API_SERVICE_VERSION_REQUEST = 'API_SERVICE_VERSION_REQUEST';
export const API_SERVICE_VERSION_SUCCESS = 'API_SERVICE_VERSION_SUCCESS';
export const API_SERVICE_VERSION_FAILURE = 'API_SERVICE_VERSION_FAILURE';

export const API_SERVICE_LOGIN_REQUEST = 'API_SERVICE_LOGIN_REQUEST';
export const API_SERVICE_LOGIN_SUCCESS = 'API_SERVICE_LOGIN_SUCCESS';
export const API_SERVICE_LOGIN_FAILURE = 'API_SERVICE_LOGIN_FAILURE';

export const API_SERVICE_LOGOUT_REQUEST = 'API_SERVICE_LOGOUT_REQUEST';
export const API_SERVICE_LOGOUT_SUCCESS = 'API_SERVICE_LOGOUT_SUCCESS';
export const API_SERVICE_LOGOUT_FAILURE = 'API_SERVICE_LOGOUT_FAILURE';

export const API_SERVICE_CSRF = 'API_SERVICE_CSRF';
export const API_SERVICE_ONLINE_USERS_COUNT = 'API_SERVICE_ONLINE_USERS_COUNT';
