export const WS_SERVICE_OPEN = 'WS_SERVICE_OPEN';
export const WS_SERVICE_ON_OPEN = 'WS_SERVICE_ON_OPEN';
export const WS_SERVICE_ON_CLOSE = 'WS_SERVICE_ON_CLOSE';
export const WS_SERVICE_ON_MESSAGE = 'WS_SERVICE_ON_MESSAGE';
export const WS_SERVICE_ON_ERROR = 'WS_SERVICE_ON_ERROR';
